Russian language support
celery/django-celery-results pull request #255
Opened 2021-11-09 20:10 UTC by ildarworld

Russian locale file is added

2021-11-10 05:41 UTC, auvipy requested changes
will need another russ speaking person to double check. can you tag someone you know

2021-11-12 09:10 UTC, ildarworld commented
> will need another russ speaking person to double check. can you tag someone you know

Guys, could you be so kind and help with double check the PR for Russian language support for django-celery-results?
@f213
@alexey-goloburdin

2021-11-12 09:20 UTC, neoromantique approved these changes
LGTM (Native Russian Speaker)

2021-11-12 09:24 UTC, svrakitin commented on locale/ru/LC_MESSAGES/django.po
> +msgstr "Данные возвращенные Заданием. Используйте поля content_encoding и content_type"
```suggestion
msgstr "Данные возвращенные Заданием. Используйте поля content_encoding и content_type для их чтения."
```

2021-11-12 09:24 UTC, svrakitin commented on locale/ru/LC_MESSAGES/django.po
> +msgstr "Поле ДатаВремя когда группа была завершена в UTC"
```suggestion
#: django_celery_results/models.py:177
msgid "Datetime field when the group result was created in UTC"
msgstr "Поле ДатаВремя если результат группы был создан в UTC"

#: django_celery_results/models.py:182
msgid "Datetime field when the group was completed in UTC"
msgstr "Поле ДатаВремя если группа была завершена в UTC"
```

2021-11-12 09:24 UTC, svrakitin commented on locale/ru/LC_MESSAGES/django.po
> +"JSON мета информаиц о Задании, такая как информация о дочерних Заданиях"
```suggestion
"JSON мета информация о Задании, такая как информация о дочерних Заданиях"
```

2021-11-12 12:45 UTC, auvipy approved these changes

2021-11-12 12:53 UTC, merged

2021-11-12 15:37 UTC, f213 commented on locale/ru/LC_MESSAGES/django.po
> +msgstr "ДатаВремя создания"
I think «Дата и время» would be more russian then «ДатаВремя»

2021-11-12 15:37 UTC, f213 commented on locale/ru/LC_MESSAGES/django.po
> +"JSON мета информация о Задании, такая как информация о дочерних Заданиях"
Should be «метаинформация» instead of «мета информация»

2021-11-12 15:37 UTC, f213 commented on locale/ru/LC_MESSAGES/django.po
> +msgstr "результаты задания"
This is `verbose_name_plural` — a name for multiple instances of a task result, so it would be better as «результаты заданий»

2021-11-12 15:37 UTC, f213 commented on locale/ru/LC_MESSAGES/django.po
> +"JSON сериалованный список таплов результата задания. Используйте .group_result() для декодирования"
[Google trends show](https://trends.google.com/trends/explore?cat=31&date=today%205-y&geo=RU&q=кортеж,тапл) that «кортеж» из more popular translation for Tuple then «тапл»

2021-11-12 16:10 UTC, auvipy commented
fixes are welcome

2021-11-12 17:52 UTC, ildarworld commented on locale/ru/LC_MESSAGES/django.po
> +msgstr "ДатаВремя создания"
Agree with all proposed changes

Will apply them ASAP

2021-11-13 09:47 UTC, f213 commented
I created #256 with suggested fixes, could you guys please check it out?