Add translation of the messages to brazilian portuguese
celery/django-celery-results pull request #278
Opened 2022-01-04 23:31 UTC by EduardoJM

This only add translation messages to brazilian portuguese.

2022-01-05 01:49 UTC, auvipy requested changes
can you please mention some fellow brazilian portugues speakers to recheck this?

2022-01-05 02:04 UTC, EduardoJM commented
> can you please mention some fellow brazilian portugues speakers to recheck this?

thats a good idea. i will made it.

2022-01-05 02:25 UTC, Fabio3rs requested changes

2022-01-05 02:25 UTC, Fabio3rs commented on django_celery_results/locale/pt_BR/LC_MESSAGES/django.po
> +msgstr "Worker que executou a tarefa"
Acredito que aqui deveria ser "Woker que executa a tarefa" ou "Worker que roda a tarefa"
Considerando que "executes" parece ser tempo presente

I think that here should be "Woker que executa a tarefa" or "Worker que roda a tarefa", seeing that "executes" is present time.

2022-01-06 00:20 UTC, EduardoJM commented
Reviewed by @Fabio3rs and by another people (who speaks in english and in brazilian portuguese, but no have github account 5618bc3).

2022-01-06 04:42 UTC, auvipy commented
OK thanks

2022-01-06 04:47 UTC, auvipy approved these changes

2022-01-06 04:49 UTC, auvipy commented
Thank you. I also have started  learning Brazilian Portuguese in duolingo & European Portuguese in youtube. though I don't understand it quite well as of yet.

2022-01-06 04:51 UTC, merged