Add retry logic for Django and Psycopg2 InterfaceErrors
celery/django-celery-results pull request #290
Opened 2022-02-24 20:08 UTC by juspence

This PR implements https://github.com/celery/django-celery-results/issues/119 in a slightly different way. It adds retry logic only for django.db.utils.InterfaceError and psycopg2.InterfaceError, which can be errors like "connection already closed".

It does not retry any DatabaseError, which can be errors like "numeric value out of range" or "foreign key check failed". See https://www.psycopg.org/docs/module.html#exceptions for more info.

exception_safe_to_retry() is overridden from the parent class: https://docs.celeryproject.org/en/stable/_modules/celery/backends/base.html#BaseBackend

This method is called when an exception is raised in _store_result() and always_retry / result_backend_always_retry is set to True. If the exception is an InterfaceError, the connection is closed as a side effect of calling exception_safe_to_retry().

Then the retry logic implemented in the parent class continues, and Django will automatically open a new connection for the next attempt to store the task result or get the task metadata.

2022-02-25 03:13 UTC, auvipy requested changes
I would like to see unit tests for this change

2022-02-28 11:28 UTC, auvipy commented
I want to add this to next release, can you please address the review comment?

2022-02-28 13:57 UTC, juspence commented
@auvipy Yes, I am working on this today since I had other tasks to finish Friday.

2022-03-01 06:46 UTC, auvipy approved these changes

2022-03-01 06:46 UTC, merged

2022-03-01 15:24 UTC, intgr commented on django_celery_results/backends/database.py
> +from psycopg2 import InterfaceError as Psycopg2InterfaceError
This adds a hard dependency on psycopg2, but django-celery-results can be used with other databases as well.

I have opened PR #292 to fix this.