Add terminate selected tasks action in admin
celery/django-celery-results pull request #449
Opened 2024-10-18 02:26 UTC by caoqianming

2024-10-21 09:25 UTC, auvipy requested changes
can you please elaborate the change a bit more? can you also verify the change?

2024-10-21 09:52 UTC, caoqianming commented
When a long task is in running state, I may need to terminate it for various reasons. So adding this action in admin is useful. I added the code and tested it and it works fine. In the beginning I was terminating tasks one by one in a for loop, later I realized that I could pass in a list, so I made some changes.

2024-10-21 09:58 UTC, auvipy requested changes
can you add tests to verify this? and do not introduce any regression?

2024-10-21 10:02 UTC, caoqianming commented
Okay, I'll try.

2024-10-21 10:54 UTC, caoqianming commented
> can you add tests to verify this? and do not introduce any regression?您能否添加测试来验证这一点？并且不引入任何回归？

Sorry, I have no idea to write this UNIT test. And i run python manage.py test with some errors in the picture. can you help me or give some suggestion, thank you 
![image](https://github.com/user-attachments/assets/c8371419-523f-4aef-b9c8-318ac927b999)

2025-02-28 16:37 UTC, AllexVeldman commented
@caoqianming unittests are run using `pytest`.

install a virtualenv with the test dependencies, make sure you are on python 3.11:
```
python -m venv .venv
. .venv/bin/activate
pip install -r requirements/default.txt -r requirements/test.txt -r requirements/test-django.txt
pytest
```

This requires a postgres database to be available on `localhost` with USER `postgres` PASSWORD `postgres` and a database with the name `postgres`. I normally use a docker image I already have running, or just run the plain docker image: https://hub.docker.com/_/postgres

Currently there are no tests testing the admin pages since there was very little functionality there, so you'll have to add a test_admin.py yourself.
If you run into issues creating the tests, ping me here and I'll see if I can spend some time on this.

2025-04-12 15:05 UTC, caoqianming commented
Hello. I add some test @AllexVeldman

2025-05-12 07:24 UTC, auvipy approved these changes

2025-05-12 07:26 UTC, auvipy commented
my concern is while this intorduce any unintended stuff? or it too risky?

2025-06-17 13:02 UTC, auvipy commented
I am going to deeply consider it again, may be by the end of this month.

2025-10-02 12:16 UTC, auvipy requested changes
can you please fix the merge conflict on test file?

2026-03-07 13:12 UTC, auvipy reviewed
looks good

2026-03-07 13:16 UTC, auvipy commented on django_celery_results/admin.py
> +            )
please check this @caoqianming if this is right or not

2026-03-07 13:17 UTC, auvipy commented on django_celery_results/admin.py
> +    terminate_task.short_description = "Terminate selected tasks"
and this

2026-03-07 13:17 UTC, auvipy commented on t/unit/test_admin.py
> +    def test_terminate_task_success(self, mock_terminate):
@caoqianming and this as well

2026-03-07 14:24 UTC, caoqianming commented on django_celery_results/admin.py
> +            )
use task(s)

2026-03-07 14:25 UTC, caoqianming commented on django_celery_results/admin.py
> +            )
add err log, but still keep err message

2026-03-07 14:25 UTC, caoqianming commented on django_celery_results/admin.py
> +    terminate_task.short_description = "Terminate selected tasks"
ok

2026-05-13 07:28 UTC, auvipy approved these changes

2026-05-13 07:32 UTC, merged

2026-05-13 07:34 UTC, auvipy commented
is there any open related issue for this?